name: vgg16
n_class: 153
pretrained: True
# ckpt_path: /media/erogullari/checkpoints/checkpoint_vgg16_celeba_attacked.pth
# ckpt_path: /media/erogullari/checkpoints/checkpoint_vgg16_celeba.pth
ckpt_path: /media/erogullari/checkpoints/checkpoint_vgg16_elements.pth