_target_: datasets.CelebAHQWithEncodings
path_data: /home/erogullari/datasets/celeba_diffae/images
path_encodings: /home/erogullari/Workspace/cav-disentanglement/variables/latents_celeba_diffae
n_samples: 202599
name: celeba