_target_: datasets.get_celeba_dataset
# data_paths: ["/Users/erogullari/datasets/"]
data_paths: ["/home/erogullari/datasets"]
normalize_data: True
shuffle: True
image_size: 224
name: celeba
localization:
  concept_ids: [0, 1, 3, 4, 5, 6, 7, 8, 9, 11, 12, 14, 15, 16, 17, 18, 19, 21, 22, 24, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38]
  concept_pair_ids: [[9, 38], [4, 31], [8, 38], [16, 9], [16, 8]]
