defaults:
  - hardware@train: local
  - dataset: celeba
  - model: vgg16
  - cav_model@cav: pattern_cav
  - _self_

experiment:
  name: disentangle_cavs
  run_heatmaps: true

train:
  learning_rate: 0.0001
  num_epochs: 200
  val_ratio: 0.1
  test_ratio: 0.1
  random_seed: 42

cav:
  cav_mode: max
  layer: features.28
  alpha: ???
  beta: null
  n_targets: 0
  optimal_init: false
  exit_criterion: orthogonality

localization:
  device: ${train.device}
  layer: ${cav.layer}
  cav_mode: ${cav.cav_mode}
  random_seed: ${train.random_seed}
  n_samples_each: 20
  concept_ids: ${dataset.localization.concept_ids}
  concept_pair_ids: ${dataset.localization.concept_pair_ids}