defaults:
  - hardware@experiment: workstation
  - dataset: celeba_attacked
  - model: vgg16
  - cav_model@cav: pattern_cav
  - _self_

experiment:
  name: pclarc
  random_seed: 42

train:
  learning_rate: 0.0001
  num_epochs: 200
  val_ratio: 0.1
  test_ratio: 0.1
  random_seed: ${experiment.random_seed}

cav:
  cav_mode: max
  layer: features.28
  alpha: ???
  beta: null
  n_targets: 0
  optimal_init: false
  exit_criterion: none

correction:
  method: PClarc