defaults:
  - hardware@experiment: workstation
  - model: diffae
  - dataset: celeba
  - cav_model@dir_model: pattern_cav
  - _self_

experiment:
  name: diffae
  seed: 42
  format: png


dir_model:
  alphas: [0.0, 0.001, 0.01, 0.1, 1.0]
  n_epochs: 200
  learning_rate: 0.0001
  random_seed: 42
  val_ratio: 0.1
  test_ratio: 0.1

move_encs:
  target_concept: Wearing_Necktie
  target_label: 1
  num_images: 5
  step_sizes: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
  move_method: clarc
  cav_mode: max
  normalize_from_data: true