defaults:
  - hardware@experiment: workstation
  - dataset@dataset: celeba_attacked
  - model: vgg16
  - cav_model@cav_model: pattern_cav
  - _self_

experiment:
  name: model_correction
  out: results/${experiment.name}/${cav_model.name}/alpha${cav.alpha}
  random_seed: 42

cav:
  cav_mode: max
  layer: features.28
  alpha: ???
  beta: null
  n_targets: 0
  optimal_init: false
  exit_criterion: none

dataset:
  artifact_type: 
  binary_target:

correction:
  method: PClarc
  layer: ${cav.layer}