defaults:
  - _self_
  - hardware@experiment: local
  - model: diffae
  - dataset@encode.dataset: celeba_diffae     # celeba_diffae or celebahq
  - dataset@move_encs.dataset: celeba_with_encodings    # celeba_with_encodings or celebahq_with_encodings
  - cav_model@dir_model: pattern_cav        # pattern_cav or multi_cav

experiment:
  name: diffae
  seed: 42
  format: png


dir_model:
  alpha: 0.00
  n_epochs: 200
  learning_rate: 0.0001
  random_seed: 42
  val_ratio: 0.1
  test_ratio: 0.0

encode:
  save_every: 8

move_encs:
  target_concept: Wearing_Necktie
  target_label: 1
  num_images: 20
  step_sizes: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0]
  move_method: clarc
  cav_mode: max
  normalize_from_data: true

decode:
  dataset: ${move_encs.dataset}