defaults:
  - hardware@train: workstation
  - dataset: elements
  - model: resnet18
  - _self_

experiment:
  name: train_model

train:
  num_epochs: 300
  learning_rate: 1.0e-3
  momentum: 0.9
  weight_decay: 1.0e-4
  val_split: 0.1
  test_split: 0.1
  random_seed: 42
  log_interval: 10
  save_best: True
